# Generated by Django 5.0.2 on 2024-03-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotauser',
            name='is_next_case',
            field=models.BooleanField(default=False),
        ),
    ]
