# Generated by Django 5.0.2 on 2024-03-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0002_rotauser_is_next_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='temporary_assignee',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='rotauser',
            name='is_next_case',
            field=models.BooleanField(default=True),
        ),
    ]
